### ISSUE TITLE
IK wigs out at certain distances from look targets

### ISSUE THREAD

**Issue by raygresko** [Black-Horizon-Studios/Emerald-AI-2024#16] opened 2024-01-16 19:43 UTC
The IK system works fine if you are within some closer radius of an AI, but at other distances it makes the head point off in multiple strange angles. This is using the same IK rig objects and values as set in the Emerald demo scenes.

**Comment by Black-Horizon-Studios** [comment] 2024-01-16 20:10
Thanks for the bug report. Is it possible for you to show a video of the issue?

**Comment by raygresko** [comment] 2024-01-16 22:10
Sure thing - here's a quick video - https://drive.google.com/file/d/1rUg1sroGAG95ER_-DTXgOuBLKHAVG8nG/view?usp=drive_link

It seems like the look target is snapping in super close to the head at some points, causing the weird rotations.

**Comment by Black-Horizon-Studios** [comment] 2024-01-17 21:48
Thanks for the video. 

It looks like your AI could be targeting their own internal colliders. It also looks like your Aim Axis could be set incorrectly. Does this happen with any of the included demo AI? 

I'd need to see the scene itself to properly identify the issue.

**Comment by raygresko** [comment] 2024-01-20 06:21
That very well could be, but one thing I notice is that it doesn't happen until the AI has seen the player, and then the player moves out of range. Before that all is working fine (the look target is off at a distance and no weirdness), and if the player moves back close again it they look at it properly. I'll try some things and remove any other colliders that may be causing this and let you know, thanks.

**Comment by raygresko** [comment] 2024-01-20 06:51
I noticed the problem wasn't happening when the AIs were turning left or right, only when they were moving/looking forward. This fixed it for me - in EmeraldInverseKinematics.UpdateIK(), line 172 where you are dealing with the Target not being within the look or distance range, I changed transform.up to transform.forward where you are calculating the lookPos in the case that the AI is not turning. This line: Vector3 LookPos = m_AimSourceParent.position + (transform.forward * EmeraldComponent.CombatComponent.DistanceFromTarget) + **transform.forward** * 5 + transform.up * LookHeightOffset;

**Comment by Black-Horizon-Studios** [comment] 2024-01-20 19:25
Thanks again for the bug report.

I was able to properly identify the cause of this bug. It was because the LookAtTarget was not being properly cleared when it exceeded an AI's detection radius. This caused EmeraldComponent.CombatComponent.DistanceFromTarget to have a value of 0 which didn't allow Vector3 LookPos to properly calculate.

This bug will be fixed with the upcoming update.

**Closed as completed by Black-Horizon-Studios** 2024-01-20 19:25 UTC
